default: &default
  adapter: postgresql 
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_database_development
  template: template0

test:
  <<: *default
  database: my_database_test
  template: template0

production:
  <<: *default
  database: my_database_production
  template: template0
